model_config_DRL = {
    'epochs': 200,
    'learning_rate': 0.05,
    'sche_gamma': 0.98,
    'data_dir': 'Data/',
    'batch_size': 512, 
    'en_nlayers': 3,
    'de_nlayers': 3,
    'hidden_dim': 128,
    'random_seed': 42,
    'num_workers': 0,
    'preprocess': 'standard',
    'diversity': True,
    'plearn': False,
    'input_info': True,
    'input_info_ratio': 0.1,
    'cl': True,
    'cl_ratio': 0.06,
    'basis_vector_num': 5,
}

model_config_MCM = {
    'epochs': 200,
    'learning_rate': 0.05,
    'sche_gamma': 0.98,
    'mask_num': 15,
    'lambda': 5,
    'data_dir': 'Data/',
    'batch_size': 512, 
    'en_nlayers': 3,
    'de_nlayers': 3,
    'hidden_dim': 256,
    'z_dim': 128,
    'mask_nlayers': 3,
    'random_seed': 42,
    'num_workers': 0,
    'preprocess': 'standard',
}

model_config_Perceiver = {
    'epochs': 200,
    'learning_rate': 0.05,
    'sche_gamma': 0.98,
    'data_dir': 'Data/',
    'batch_size': 512, 
    'num_heads': 4,
    'num_layers': 4,
    'hidden_dim': 64,
    'mlp_ratio': 4.0,
    'dropout_prob': 0.0,
    'drop_col_prob': 0.3,
    'num_workers': 0,
    'preprocess': 'standard',
}