default: 
  train_config:
    data_dir: 'Data/' 
    epochs: 200
    learning_rate: 0.05
    sche_gamma: 0.98
    batch_size: 512
    preprocess: 'standard'
    random_seed: 42
    num_workers: 0
  model_config:
    depth: 3
    hidden_dim: 64
    num_memories: null

census:
  batch_size: 2048

fraud:
  batch_size: 2048  