default: 
  data_dir: 'Data/'
  epochs: 200
  learning_rate: 0.05
  sche_gamma: 0.98
  batch_size: 512
  depth: 3
  hidden_dim: 64
  random_seed: 42
  num_workers: 0
  preprocess: 'standard'

census:
  batch_size: 2048

fraud:
  batch_size: 2048  