default:
  data_dir: 'Data/'
  random_seed: 42
  num_workers: 0
  batch_size: 512
  preprocess: 'standard'

arrhythmia:
  batch_size: 32

breastw:
  batch_size: 32

cardio:
  batch_size: 512

census:
  batch_size: 2048

campaign:
  batch_size: 512

cardiotocography:
  batch_size: 512

fraud:
  batch_size: 2048

glass:
  batch_size: 32

ionosphere:
  batch_size: 32
  
mammography:
  batch_size: 512

nslkdd:
  batch_size: 512

optdigits:
  batch_size: 512

pima:
  batch_size: 32

pendigits:
  batch_size: 512

satellite:
  batch_size: 512

satimage-2:
  batch_size: 512

shuttle:
  batch_size: 512

32_shuttle_if_0.1_42:
  batch_size: 512

32_shuttle_if_0.3_42:
  batch_size: 512

32_shuttle_if_0.5_42:
  batch_size: 512


thyroid:
  batch_size: 128

wbc:
  batch_size: 32

wine:
  batch_size: 32