default: 
  data_dir: 'Data/'
  epochs: 200
  learning_rate: 0.0001
  sche_gamma: 0.98
  batch_size: 512
  en_nlayers: 3
  de_nlayers: 3
  hidden_dim: 256
  random_seed: 42
  num_workers: 0
  preprocess: 'standard'
  patch_size: 1
  overlap: 0
  
  
arrhythmia:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 64

breastw:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 64

cardio:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 128

census:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 1024

campaign:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 2048

cardiotocography:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 128

fraud:
  epochs: 200
  hidden_dim: 512
  patch_size: 15
  overlap: 8
  batch_size: 2048

glass:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 64

ionosphere:
  epochs: 200
  hidden_dim: 512
  patch_size: 17
  overlap: 9
  batch_size: 64

mammography:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 2048

nslkdd:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 2048

optdigits:
  epochs: 200
  hidden_dim: 512
  patch_size: 32
  overlap: 16
  batch_size: 128

pima:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 128

pendigits:
  epochs: 200
  hidden_dim: 512
  patch_size: 8
  overlap: 4
  batch_size: 128

satellite:
  epochs: 200
  hidden_dim: 512
  patch_size: 18
  overlap: 9
  batch_size: 512

satimage-2:
  epochs: 200
  hidden_dim: 512
  patch_size: 18
  overlap: 9
  batch_size: 512

shuttle:
  epochs: 200
  hidden_dim: 512
  patch_size: 5
  overlap: 3
  batch_size: 2048

thyroid:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 512

wbc:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 64

wine:
  epochs: 100
  hidden_dim: 128
  patch_size: 1
  overlap: 0
  batch_size: 64