default: 
  train_config:
    data_dir: 'Data/'
    epochs: 200
    learning_rate: 0.05
    sche_gamma: 0.98
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
    batch_size: 512
  model_config:
    diversity: True
    plearn: False
    input_info: True
    input_info_ratio: 0.1
    cl: True
    cl_ratio: 0.06
    basis_vector_num: 5
    en_nlayers: 3
    de_nlayers: 3
    hidden_dim: 256
    
arrhythmia:
  learning_rate: 0.05

breastw:
  learning_rate: 0.05

cardio:
  learning_rate: 0.05

census:
  learning_rate: 0.05
  batch_size: 2048

campaign:
  learning_rate: 0.05

cardiotocography:
  learning_rate: 0.05

fraud:
  learning_rate: 0.05
  batch_size: 2048

glass:
  learning_rate: 0.05

ionosphere:
  learning_rate: 0.05

mammography:
  learning_rate: 0.05

nslkdd:
  learning_rate: 0.05

optdigits:
  learning_rate: 0.05

pima:
  learning_rate: 0.05

pendigits:
  learning_rate: 0.05

satellite:
  learning_rate: 0.05

satimage:
  learning_rate: 0.05

shuttle:
  learning_rate: 0.05

thyroid:
  learning_rate: 0.05

wbc:
  learning_rate: 0.05

wine:
  learning_rate: 0.05