default: 
  data_dir: 'Data/'
  epochs: 200
  learning_rate: 0.05
  sche_gamma: 0.98
  mask_num: 15
  lambda: 5
  batch_size: 512
  en_nlayers: 3
  de_nlayers: 3
  hidden_dim: 256
  z_dim: 128
  mask_nlayers: 3
  random_seed: 42
  num_workers: 0
  preprocess: 'standard'

wbc:
  epochs: 200
  learning_rate: 0.05
  mask_num: 15
  lambda: 5

cardio:
  epochs: 200
  learning_rate: 0.05
  mask_num: 10
  lambda: 100

campaign:
  epochs: 200
  learning_rate: 0.001
  mask_num: 15
  lambda: 200

cardiotocography:
  epochs: 200
  learning_rate: 0.001
  mask_num: 15
  lambda: 1

donors:
  epochs: 200
  learning_rate: 0.01
  mask_num: 15
  lambda: 1

thyroid:
  epochs: 200
  learning_rate: 0.01
  mask_num: 15
  lambda: 1

optdigits:
  epochs: 200
  learning_rate: 0.01
  mask_num: 15
  lambda: 10

satimage-2:
  epochs: 200
  learning_rate: 0.001
  mask_num: 15
  lambda: 10

pima:
  epochs: 200
  learning_rate: 0.1
  mask_num: 10
  lambda: 1

pendigits:
  epochs: 200
  learning_rate: 0.01
  mask_num: 15
  lambda: 10

breastw:
  epochs: 200
  learning_rate: 0.005
  mask_num: 15
  lambda: 10

arrhythmia:
  epochs: 200
  learning_rate: 0.001
  mask_num: 15
  lambda: 5

ionosphere:
  epochs: 200
  learning_rate: 0.01
  mask_num: 15
  lambda: 10

mammography:
  epochs: 200
  learning_rate: 0.05
  mask_num: 15
  lambda: 200

glass:
  epochs: 200
  learning_rate: 0.05
  mask_num: 15
  lambda: 100

wine:
  epochs: 200
  learning_rate: 0.01
  mask_num: 15
  lambda: 50

shuttle:
  epochs: 200
  learning_rate: 0.0001
  mask_num: 15
  lambda: 1

satellite:
  epochs: 200
  learning_rate: 0.005
  mask_num: 15
  lambda: 5

nslkdd:
  epochs: 100
  learning_rate: 0.01
  mask_num: 15
  lambda: 20

fraud:
  epochs: 50
  learning_rate: 0.0001
  mask_num: 15
  lambda: 1

census:
  epochs: 200
  learning_rate: 0.01
  mask_num`: 15
  lambda: 1