default: 
  train_config:
    data_dir: 'Data/'
    epochs: 200
    learning_rate: 0.05
    sche_gamma: 0.98
    batch_size: 512
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
  model_config:
    num_heads: 4
    num_latents: null
    depth: 4
    hidden_dim: 8
    mlp_ratio: 4.0
    dropout_prob: 0.0
    mask_num: 15
    diversity_loss_weight: 5


wbc:
  mask_num: 15
  lambda: 5

cardio:
  mask_num: 10
  lambda: 100

campaign:
  mask_num: 15
  lambda: 200

cardiotocography:
  mask_num: 15
  lambda: 1

donors:
  mask_num: 15
  lambda: 1

thyroid:
  mask_num: 15
  lambda: 1

optdigits:
  mask_num: 15
  lambda: 10

satimage-2:
  mask_num: 15
  lambda: 10

pima:
  mask_num: 10
  lambda: 1

pendigits:
  mask_num: 15
  lambda: 10

breastw:
  mask_num: 15
  lambda: 10

arrhythmia:
  mask_num: 15
  lambda: 5

ionosphere:
  mask_num: 15
  lambda: 10

mammography:
  mask_num: 15
  lambda: 200

glass:
  mask_num: 15
  lambda: 100

wine:
  mask_num: 15
  lambda: 50

shuttle:
  mask_num: 15
  lambda: 1

satellite:
  mask_num: 15
  lambda: 5

nslkdd:
  mask_num: 15
  lambda: 20

fraud:
  mask_num: 15
  lambda: 1
  batch_size: 2048

census:
  mask_num: 5
  lambda: 1
  batch_size: 1024