default: 
  train_config:
    data_dir: 'Data/'
    epochs: 200
    learning_rate: 0.05
    sche_gamma: 0.98
    batch_size: 512
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
  model_config:
    hidden_dim: 256
    en_nlayers: 3
    de_nlayers: 3
    num_memories: null
    temperature: 1
    sim_type: 'cos'
    
census:
  batch_size: 2048

fraud:
  batch_size: 2048