default: 
  data_dir: 'Data/'
  epochs: 200
  learning_rate: 0.05
  sche_gamma: 0.98
  batch_size: 512
  depth: 3
  temperature: 1
  hidden_dim: 256
  sim_type: 'cos'
  random_seed: 42
  num_workers: 0
  preprocess: 'standard'