default: 
  data_dir: 'Data/'
  epochs: 200
  learning_rate: 0.05
  sche_gamma: 0.98
  batch_size: 512
  num_heads: 4
  depth: 4
  hidden_dim: 8
  mlp_ratio: 4.0
  dropout_prob: 0.0
  random_seed: 42
  num_workers: 0
  preprocess: 'standard'