default: 
  train_config:
    data_dir: 'Data/'
    epochs: 200
    learning_rate: 0.001
    sche_gamma: 0.98
    random_seed: 42
    num_workers: 0
    preprocess: 'standard'
    batch_size: 512
  model_config:
    num_latents: null
    num_heads: 4
    depth: 4
    hidden_dim: 64
    mlp_ratio: 4.0
    dropout_prob: 0.0
    num_latents: null
    input_info_ratio: 0.1
    cl_ratio: 0.06
    num_basis_vectors: 5

    
census:
  batch_size: 2048

fraud:
  batch_size: 2048